apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: raglens-cluster
  region: us-east-1
  version: "1.35"
 
managedNodeGroups:
  - name: raglens-ng
<<<<<<< HEAD
    instanceType: t3.small
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
=======
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 30
>>>>>>> 4bb5213a355bd6dcb862f2d1306512b034291844
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true
 
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
 
iam:
  withOIDC: true

<<<<<<< HEAD

=======
>>>>>>> 4bb5213a355bd6dcb862f2d1306512b034291844
