apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: raglens-cluster
  region: us-east-1
  version: "1.30"
 
managedNodeGroups:
  - name: raglens-ng

    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20

    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true
 
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
