apiVersion: apps/v1
kind: Deployment
metadata:
  name: raglens-backend
  namespace: raglens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raglens-backend
  template:
    metadata:
      labels:
        app: raglens-backend
    spec:
      containers:
        - name: backend
          image: souravsrinivas2912/raglens-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: raglens-aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: raglens-aws
                  key: AWS_SECRET_ACCESS_KEY
            - name: SARVAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: raglens-env
                  key: SARVAM_API_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: raglens-env
                  key: GROQ_API_KEY
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: raglens-env
                  key: HF_TOKEN
            - name: ENV
              value: production
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /api/health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          
