apiVersion: apps/v1
kind: Deployment
metadata:
  name: raglens-backend
  namespace: raglens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raglens-backend
  template:
    metadata:
      labels:
        app: raglens-backend
    spec:
      containers:
        - name: backend
          image: souravsrinivas2912/raglens-backend:latest
          ports:
            - containerPort: 8003
          env:
            - name: ENV
              value: production
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 5


