apiVersion: v1
kind: Service
metadata:
  name: raglens-backend-svc
  namespace: raglens
spec:
  selector:
    app: raglens-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP


