apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raglens-ingress
  namespace: raglens
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - www.ssgudl.shop
      secretName: raglens-tls
  rules:
    - host: www.ssgudl.shop
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: raglens-backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: raglens-frontend-svc
                port:
                  number: 80
 


