apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raglens-chromadb-pvc
  namespace: raglens
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi